### ISSUE TITLE
Can't connect to device due to a exception

### ISSUE THREAD

**Issue by dantovalphas** [kakone/GoogleCast#42]
I test the package with .NET Maui android app, when i selected the device can't connect due to a exception... 

```
[monodroid-assembly] open_from_bundles: failed to load assembly GoogleCast.dll
Loaded assembly: /data/data/com.alphas.growingfamily/files/.__override__/GoogleCast.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.Net.NetworkInformation.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Net.Sockets.dll
Loaded assembly: /data/data/com.alphas.growingfamily/files/.__override__/System.Net.NetworkInformation.dll [External]
Loaded assembly: /data/data/com.alphas.growingfamily/files/.__override__/System.Net.Sockets.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Zeroconf.dll
Loaded assembly: /data/data/com.alphas.growingfamily/files/.__override__/Zeroconf.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.Reactive.dll
Loaded assembly: /data/data/com.alphas.growingfamily/files/.__override__/System.Reactive.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Win32.Primitives.dll
Loaded assembly: /data/data/com.alphas.growingfamily/files/.__override__/Microsoft.Win32.Primitives.dll [External]
[s.growingfamily] type=1400 audit(0.0:1203587): avc: denied { ioctl } for path="socket:[2849895]" dev="sockfs" ino=2849895 ioctlcmd=0x8946 scontext=u:r:untrusted_app:s0:c244,c256,c512,c768 tcontext=u:r:untrusted_app:s0:c244,c256,c512,c768 tclass=udp_socket permissive=0
[monodroid-assembly] open_from_bundles: failed to load assembly System.Threading.ThreadPool.dll
Loaded assembly: /data/data/com.alphas.growingfamily/files/.__override__/System.Threading.ThreadPool.dll [External]
Thread started: .NET Sockets #12
[Choreographer] Skipped 37 frames!  The application may be doing too much work on its main thread.
[mali_winsys] EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
[monodroid-assembly] open_from_bundles: failed to load assembly System.Net.Security.dll
Loaded assembly: /data/data/com.alphas.growingfamily/files/.__override__/System.Net.Security.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.Security.Cryptography.dll
Loaded assembly: /data/data/com.alphas.growingfamily/files/.__override__/System.Security.Cryptography.dll [External]
[libEGL] EGLNativeWindowType 0xcd21b008 disconnect failed
[InputEventReceiver] Attempted to finish an input event but the input event receiver has already been disposed.
[monodroid-assembly] open_from_bundles: failed to load assembly System.Collections.NonGeneric.dll
Loaded assembly: /data/data/com.alphas.growingfamily/files/.__override__/System.Collections.NonGeneric.dll [External]
[System.err] javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
[System.err] 	at com.google.android.gms.org.conscrypt.SSLUtils.toSSLHandshakeException(:com.google.android.gms@230617024@23.06.17 (100300-511787759):2)
[System.err] 	at com.google.android.gms.org.conscrypt.ConscryptEngine.convertException(:com.google.android.gms@230617024@23.06.17 (100300-511787759):1)
[System.err] 	at com.google.android.gms.org.conscrypt.ConscryptEngine.readPlaintextData(:com.google.android.gms@230617024@23.06.17 (100300-511787759):4)
[System.err] 	at com.google.android.gms.org.conscrypt.ConscryptEngine.unwrap(:com.google.android.gms@230617024@23.06.17 (100300-511787759):30)
[System.err] 	at com.google.android.gms.org.conscrypt.ConscryptEngine.unwrap(:com.google.android.gms@230617024@23.06.17 (100300-511787759):46)
[System.err] 	at com.google.android.gms.org.conscrypt.ConscryptEngine.unwrap(:com.google.android.gms@230617024@23.06.17 (100300-511787759):2)
[System.err] 	at mono.java.lang.RunnableImplementor.n_run(Native Method)
[System.err] 	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:31)
[System.err] 	at android.os.Handler.handleCallback(Handler.java:873)
[System.err] 	at android.os.Handler.dispatchMessage(Handler.java:99)
[System.err] 	at android.os.Looper.loop(Looper.java:211)
[System.err] 	at android.app.ActivityThread.main(ActivityThread.java:6769)
[System.err] 	at java.lang.reflect.Method.invoke(Native Method)
[System.err] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
[System.err] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
[System.err] Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
[System.err] 	at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:668)
[System.err] 	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:546)
[System.err] 	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:502)
[System.err] 	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:425)
[System.err] 	at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:360)
[System.err] 	at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:102)
[System.err] 	at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:104)
[System.err] 	at java.lang.reflect.Method.invoke(Native Method)
[System.err] 	at com.google.android.gms.org.conscrypt.Platform.checkTrusted(:com.google.android.gms@230617024@23.06.17 (100300-511787759):2)
[System.err] 	at com.google.android.gms.org.conscrypt.Platform.checkServerTrusted(:com.google.android.gms@230617024@23.06.17 (100300-511787759):5)
[System.err] 	at com.google.android.gms.org.conscrypt.ConscryptEngine.verifyCertificateChain(:com.google.android.gms@230617024@23.06.17 (100300-511787759):6)
[System.err] 	at com.google.android.gms.org.conscrypt.NativeCrypto.ENGINE_SSL_read_direct(Native Method)
[System.err] 	at com.google.android.gms.org.conscrypt.NativeSsl.readDirectByteBuffer(:com.google.android.gms@230617024@23.06.17 (100300-511787759):2)
[System.err] 	at com.google.android.gms.org.conscrypt.ConscryptEngine.readPlaintextDataDirect(:com.google.android.gms@230617024@23.06.17 (100300-511787759):0)
[System.err] 	at com.google.android.gms.org.conscrypt.ConscryptEngine.readPlaintextDataHeap(:com.google.android.gms@230617024@23.06.17 (100300-511787759):3)
[System.err] 	at com.google.android.gms.org.conscrypt.ConscryptEngine.readPlaintextData(:com.google.android.gms@230617024@23.06.17 (100300-511787759):3)
[System.err] 	... 12 more
[System.err] Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
[System.err] 	... 28 more
[monodroid-assembly] open_from_bundles: failed to load assembly es-419/System.Net.Security.resources.dll
[monodroid-assembly] open_from_bundles: failed to load assembly es-419/System.Net.Security.resources.dll
[monodroid-assembly] open_from_bundles: failed to load assembly es/System.Net.Security.resources.dll
[monodroid-assembly] open_from_bundles: failed to load assembly es/System.Net.Security.resources.dll
[DOTNET] Authentication failed, see inner exception.
```

**Comment by vhugogarcia** [comment]
Hello @dantovalphas , I'm facing the same issue. Did you find a solution for this?

Thanks in advance

**Comment by vhugogarcia** [comment]
Hello @dantovalphas , I fixed the Android issue by applying this workaround in .NET MAUI: https://stackoverflow.com/a/71196389/1867796

I could not find a solution for iOS, if you found any, please let me know :)

Thanks in advance.
